### ISSUE TITLE
Security vulnerability: Move private key out of code

### ISSUE THREAD

**Issue by Dandigit** [yepicsend/api#5]
**Describe the bug**
Currently, there is a serious security vulnerability in the code: the private key used to sign authentication tokens is a constant in the code with a really obvious value ('PrivateKey'). This was done for testing, but now it should be moved to a config file.

**Comment by SimpleBinary** [comment]
@Dandigit Ok, I'll move this to the rewrite project.

**Comment by Dandigit** [comment]
Fixed in #6.
